skip:
- rule: github_action_from_unverified_creator_used
  purl:
  - pkg:githubactions/actions-rust-lang/setup-rust-toolchain
  - pkg:githubactions/eclipse-dash/quevee
  - pkg:githubactions/eclipse-uprotocol/ci-cd
  - pkg:githubactions/joutvhu/get-release
  - pkg:githubactions/lycheeverse/lychee-action
  - pkg:githubactions/rust-lang/crates-io-auth-action
  - pkg:githubactions/xom9ikk/dotenv
