[package]
name = "up-unix-domain-socket-transport"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
up-frame-codec = { path = "../up-frame-codec" }
up-rust = { workspace = true, features = ["up-core-types"] }
tokio = { version = "1.52.3", features = ["net", "io-util", "rt", "macros", "sync", "time"] }
async-trait = "0.1"
anyhow = "1.0"

[dev-dependencies]
up-rust = { workspace = true, features = ["test-util"] }
