/********************************************************************************
 * Copyright (c) 2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

use super::SerializationError;
use protobuf::{well_known_types::any::Any, Message, MessageFull};

/// A type that can be mapped to and from a protobuf.
pub trait ProtobufMappable: Sized {
    /// Parses an instance of this type from the given protobuf bytes.
    ///
    /// # Arguments
    ///
    /// * `proto` - The protobuf message.
    ///
    /// # Errors
    ///
    /// Returns an error if the given bytes cannot be parsed as a protobuf.
    fn parse_from_protobuf_bytes(proto: &[u8]) -> Result<Self, SerializationError>;
    /// Parses an instance of this type from the given packed protobuf bytes.
    ///
    /// # Arguments
    ///
    /// * `proto` - The protobuf _Any_ message containing the actual message packed inside.
    ///
    /// # Errors
    ///
    /// Returns an error if the given bytes cannot be parsed to a protobuf _Any_ message
    /// or if the contained message cannot be unpacked to the expected type.
    fn parse_from_packed_protobuf_bytes(proto: &[u8]) -> Result<Self, SerializationError>;
    /// Serializes this instance to protobuf bytes.
    ///
    /// # Errors
    ///
    /// Returns an error if this instance cannot be serialized to protobuf bytes.
    fn write_to_protobuf_bytes(&self) -> Result<Vec<u8>, SerializationError>;
    /// Serializes this instance to packed protobuf bytes.
    ///
    /// # Errors
    ///
    /// Returns an error if this instance cannot be serialized to packed protobuf bytes.
    fn write_to_packed_protobuf_bytes(&self) -> Result<Vec<u8>, SerializationError>;
}

/// Blanket implementation for all types that have been generated by the
/// [protobuf](https://crates.io/crates/protobuf) crate.
impl<T: MessageFull> ProtobufMappable for T {
    fn parse_from_protobuf_bytes(proto: &[u8]) -> Result<Self, SerializationError> {
        Ok(T::parse_from_bytes(proto)?)
    }

    fn parse_from_packed_protobuf_bytes(proto: &[u8]) -> Result<Self, SerializationError> {
        let any = Any::parse_from_bytes(proto)?;
        match any.unpack() {
            Ok(Some(v)) => Ok(v),
            Ok(None) => Err(SerializationError::new(
                "cannot unpack protobuf, type mismatch".to_string(),
            )),
            Err(e) => Err(SerializationError::from(e)),
        }
    }

    fn write_to_protobuf_bytes(&self) -> Result<Vec<u8>, SerializationError> {
        T::write_to_bytes(self).map_err(SerializationError::from)
    }

    fn write_to_packed_protobuf_bytes(&self) -> Result<Vec<u8>, SerializationError> {
        Any::pack(self)
            .and_then(|any| any.write_to_bytes())
            .map_err(SerializationError::from)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use protobuf::well_known_types::{timestamp::Timestamp, wrappers::StringValue};

    #[test]
    fn test_write_to_protobuf_bytes_works_for_message_full() {
        let payload = StringValue {
            value: "hello".to_string(),
            ..Default::default()
        };
        let bytes = payload.write_to_protobuf_bytes().unwrap();
        let deserialized = StringValue::parse_from_protobuf_bytes(&bytes).unwrap();
        assert_eq!(deserialized.value, "hello");
    }

    #[test]
    fn test_write_to_packed_protobuf_bytes_works_for_message_full() {
        let payload = StringValue {
            value: "hello".to_string(),
            ..Default::default()
        };
        let bytes = payload.write_to_packed_protobuf_bytes().unwrap();
        let deserialized = StringValue::parse_from_packed_protobuf_bytes(&bytes).unwrap();
        assert_eq!(deserialized.value, "hello");
    }

    #[test]
    fn test_parse_from_packed_protobuf_bytes_fails_for_wrong_message_type() {
        let payload = StringValue {
            value: "hello".to_string(),
            ..Default::default()
        };
        let bytes = payload.write_to_packed_protobuf_bytes().unwrap();
        assert!(Timestamp::parse_from_packed_protobuf_bytes(&bytes)
            .is_err_and(|e| { matches!(e, SerializationError { .. }) }));
    }
}
