syntax = "proto3";

package uprotocol.bench.v1;

import "uprotocol/bench/v1/common.proto";

message CanClassicFrame {
  BenchHeader header = 1;
  uint32 interface_id = 2;
  uint32 can_id = 3;
  bool is_extended_id = 4;
  bool is_remote_request = 5;
  bool is_error_frame = 6;
  uint32 len = 7;
  uint32 len8_dlc = 8;
  uint64 bus_timestamp_ns = 9;
  bytes data = 10;
  uint32 checksum = 11;
}

message CanFdFrame {
  BenchHeader header = 1;
  uint32 interface_id = 2;
  uint32 can_id = 3;
  bool is_extended_id = 4;
  bool is_remote_request = 5;
  bool is_error_frame = 6;
  bool bitrate_switch = 7;
  bool error_state_indicator = 8;
  uint32 len = 9;
  uint64 bus_timestamp_ns = 10;
  bytes data = 11;
  uint32 checksum = 12;
}
