# ********************************************************************************
#  Copyright (c) 2026 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

name: GitHub Actions Policy Checks

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches: [main]
    paths:
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy-checks:
    permissions:
      contents: read
      security-events: write
    uses: eclipse-uprotocol/ci-cd/.github/workflows/github-actions-policy-checks.yaml@ad3f99eac0675c714f08c473412dae14d9fecaa8
