on:
  pull_request:
  push:
    branches:
      - main

name: Test with Code Coverage

jobs:
  test:
    name: Test
    env:
      PROJECT_NAME_UNDERSCORE: uprotocol_sdk
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: --cfg uuid_unstable -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
      RUSTDOCFLAGS: -Cpanic=abort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: |
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
      - name: Generate test result and coverage report
        run: |
          cargo install cargo2junit grcov;
          cargo test $CARGO_OPTIONS -- -Z unstable-options --format json | cargo2junit > results.xml;
          zip -0 ccov.zip `find . \( -name "$PROJECT_NAME_UNDERSCORE*.gc*" \) -print`;
          grcov ccov.zip -s . -t lcov --llvm --ignore-not-existing --ignore "/*" --ignore "tests/*" --ignore "target/*" -o lcov.info;
          mkdir -p reports;
          mv results.xml reports/;
          mv lcov.info reports/;
      - name: Commit and push reports
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./reports/*
          git commit -m "Add test and coverage reports" || echo "No changes to commit"
          git push
      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: results.xml
          job_summary: true
      - name: Upload test coverage
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: Test Coverage
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: lcov.info
          job_summary: true
#      - name: Upload to CodeCov
#        uses: codecov/codecov-action@v1
#        with:
#          # required for private repositories:
#          # token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./lcov.info
#          fail_ci_if_error: true